[package]
name = "nn"
version = "0.1.0"
authors = ["David Garcia <davidgmorillop@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
statrs = "0.15.0"
rand = "0.8.4"
lazy_static = "1.4.0"